<a href="https://colab.research.google.com/github/frostfire05/frostfire_arrives/blob/main/multivariateLinear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#LINEAR REGRESSION FOR MULTIPLE VARIABLES

In [1]:
import pandas as pd
import numpy as py
from sklearn import linear_model

In [3]:
df = pd.read_csv('house_prices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [4]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

4

In [8]:
from sklearn.impute import SimpleImputer
my_imputer = SimpleImputer()
imputed_x = pd.DataFrame(my_imputer.fit_transform(df))
imputed_x.columns = df.columns
imputed_x

area  bedrooms   age     price
0  2600.0       3.0  20.0  550000.0
1  3000.0       4.0  15.0  565000.0
2  3200.0       4.2  18.0  610000.0
3  3600.0       3.0  30.0  595000.0
4  4000.0       5.0   8.0  760000.0
5  4100.0       6.0   8.0  810000.0

In [9]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [10]:
model = linear_model.LinearRegression()

In [12]:
model.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [13]:
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [14]:
model.intercept_

np.float64(221323.00186540396)

In [15]:
model.predict([[3000,3,40]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

#HIRING PREDICTION

In [16]:
data = pd.read_csv('hiring.csv')
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [17]:
data.experience = data.experience.fillna('zero')
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [18]:
!pip install word2number

  Preparing metadata (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5568 sha256=57ae51011b5c80fbeca0802dc7b8140977a8a225c7d5e6f6462769e3936ae217
  Stored in directory: /root/.cache/pip/wheels/5b/79/fb/d25928e599c7e11fe4e00d32048cd74933f34a74c633d2aea6
Successfully built word2number


In [25]:
import word2number.w2n as w2n
data['experience'] = data['experience'].astype(str).apply(w2n.word_to_num)
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [26]:
my_imputer2 = SimpleImputer()
imputed_d = pd.DataFrame(my_imputer.fit_transform(data))
imputed_d.columns = data.columns
imputed_d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         0.0               8.000000                         9.0    50000.0
1         0.0               8.000000                         6.0    45000.0
2         5.0               6.000000                         7.0    60000.0
3         2.0              10.000000                        10.0    65000.0
4         7.0               9.000000                         6.0    70000.0
5         3.0               7.000000                        10.0    62000.0
6        10.0               7.857143                         7.0    72000.0
7        11.0               7.000000                         8.0    80000.0

In [27]:
model_2 = linear_model.LinearRegression()
model_2.fit(imputed_d[['experience','test_score(out of 10)','interview_score(out of 10)']],imputed_d['salary($)'])


LinearRegression()

In [28]:
model.predict([[2,9,6]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([412656.73999894])

In [29]:
model.predict([[12,10,10]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([424239.37286177])